/**
 * @param { import('knex').Knex } knex
 */
export async function seed(knex) {
  await knex("questions").del();
  const rows = [
    {
      text: "How many players are on the field for one team in a standard soccer match?",
      option_a: "9",
      option_b: "10",
      option_c: "11",
      option_d: "12",
      correct_index: 2,
      difficulty: "easy",
    },
    {
      text: "What is the duration of each half in a standard adult professional soccer match?",
      option_a: "40 minutes",
      option_b: "45 minutes",
      option_c: "50 minutes",
      option_d: "60 minutes",
      correct_index: 1,
      difficulty: "easy",
    },
    {
      text: "Which player is allowed to use their hands inside the penalty area?",
      option_a: "Defender",
      option_b: "Striker",
      option_c: "Goalkeeper",
      option_d: "Midfielder",
      correct_index: 2,
      difficulty: "easy",
    },
    {
      text: "What is a yellow card primarily used for?",
      option_a: "Goal celebration",
      option_b: "Substituting a player",
      option_c: "Warning for misconduct",
      option_d: "Ending the match",
      correct_index: 2,
      difficulty: "easy",
    },
    {
      text: "A direct free kick is awarded inside the penalty box for a foul committed by the defending team. What is typically awarded?",
      option_a: "Corner kick",
      option_b: "Penalty kick",
      option_c: "Throw-in",
      option_d: "Indirect free kick",
      correct_index: 1,
      difficulty: "normal",
    },
    {
      text: "What is the maximum number of substitutions allowed in most top-tier league matches (as commonly used)?",
      option_a: "3",
      option_b: "5",
      option_c: "7",
      option_d: "Unlimited",
      correct_index: 1,
      difficulty: "normal",
    },
    {
      text: "Which club has won the most UEFA Champions League titles (European Cup era included)?",
      option_a: "AC Milan",
      option_b: "Bayern Munich",
      option_c: "Real Madrid",
      option_d: "Liverpool",
      correct_index: 2,
      difficulty: "normal",
    },
    {
      text: "The FIFA World Cup is held every ___ years.",
      option_a: "2",
      option_b: "3",
      option_c: "4",
      option_d: "5",
      correct_index: 2,
      difficulty: "easy",
    },
    {
      text: "What is 'offside' primarily about?",
      option_a: "Ball crossing the sideline",
      option_b: "Attacker nearer to goal line than ball and second-last opponent when receiving",
      option_c: "Goalkeeper leaving the box",
      option_d: "Too many players on the field",
      correct_index: 1,
      difficulty: "normal",
    },
    {
      text: "Which country hosted the 2022 FIFA World Cup?",
      option_a: "Russia",
      option_b: "Brazil",
      option_c: "Qatar",
      option_d: "Japan",
      correct_index: 2,
      difficulty: "easy",
    },
    {
      text: "What is a 'hat-trick' in soccer?",
      option_a: "Three assists in one match",
      option_b: "Three goals by the same player in one match",
      option_c: "Three yellow cards",
      option_d: "Three saves by the goalkeeper",
      correct_index: 1,
      difficulty: "easy",
    },
    {
      text: "What does VAR stand for in modern soccer officiating?",
      option_a: "Video Assistant Referee",
      option_b: "Verified Action Review",
      option_c: "Virtual Attack Rule",
      option_d: "Victory Advantage Rule",
      correct_index: 0,
      difficulty: "easy",
    },
    {
      text: "Which surface is standard for professional outdoor soccer?",
      option_a: "Ice",
      option_b: "Natural grass or approved artificial turf",
      option_c: "Sand only",
      option_d: "Wood court",
      correct_index: 1,
      difficulty: "easy",
    },
    {
      text: "A throw-in is taken when the ball fully crosses which boundary?",
      option_a: "Goal line",
      option_b: "Touchline (sideline)",
      option_c: "Halfway line",
      option_d: "Penalty arc",
      correct_index: 1,
      difficulty: "easy",
    },
    {
      text: "What is a 'clean sheet' for a goalkeeper/team?",
      option_a: "Scoring three goals",
      option_b: "Conceding no goals in a match",
      option_c: "Saving a penalty",
      option_d: "Winning by forfeit",
      correct_index: 1,
      difficulty: "normal",
    },
  ];
  await knex("questions").insert(rows);
}
